version: '3.8'

services:
  media-converter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whats-media-converter
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - PORT=8080
      - GOGC=100
      - GOMEMLIMIT=2GiB
      - GOMAXPROCS=0
      - MAX_WORKERS=0
      - BUFFER_POOL_SIZE=100
      - BUFFER_SIZE=10485760
      - REQUEST_TIMEOUT=5m
      - BODY_LIMIT=524288000
      - READ_TIMEOUT=5m
      - WRITE_TIMEOUT=5m
      - DOWNLOAD_TIMEOUT=30s
      - MAX_IDLE_CONNS=100
      - IDLE_CONN_TIMEOUT=90s
      - AUDIO_BITRATE=128k
      - MAX_AUDIO_SIZE=104857600
      - DEFAULT_IMAGE_QUALITY=95
      - DEFAULT_MAX_WIDTH=1920
      - DEFAULT_MAX_HEIGHT=1920
      - MAX_IMAGE_SIZE=209715200
      - LOG_LEVEL=info
      - ENABLE_PERFORMANCE_LOGS=true
      - ENABLE_HEALTH_CHECK=true
      - ENABLE_STATS_ENDPOINT=true
      - ENABLE_CORS=true
      - ENABLE_API_AUTH=false
      - API_KEY=
      - ENABLE_RATE_LIMITING=false
      - RATE_LIMIT=1000
      # S3 Configuration
      - S3_ENABLED=true
      - S3_PROVIDER=minio
      - S3_ENDPOINT=http://minio:9000
      - S3_PUBLIC_ENDPOINT=http://localhost:9001
      - S3_REGION=us-east-1
      - S3_BUCKET=uploads
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin123
      - S3_PATH_STYLE=true
      - S3_PUBLIC_READ=true
      - S3_EXPIRATION_DAYS=0
      - S3_MULTIPART_THRESHOLD=5242880
      - S3_CHUNK_SIZE=10485760
      - S3_MAX_CONCURRENT_UPLOADS=3
      - S3_UPLOAD_TIMEOUT=1h
      - S3_RETRY_COUNT=3
      - S3_KEY_PREFIX=uploads/
      - S3_USE_TIMESTAMP_IN_KEY=true
      - S3_USE_UUID_IN_KEY=true
      - S3_PRESERVE_FILENAME=true
      - S3_ALLOWED_CONTENT_TYPES=
      - S3_MAX_FILE_SIZE=0
      - S3_SCAN_UPLOADS=false
      - S3_ENABLE_METRICS=true
      - S3_LOG_UPLOADS=true
    volumes:
      # Use tmpfs for temporary files (RAM storage)
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 4G
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 4G
    depends_on:
      - minio
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 6G
        reservations:
          cpus: '2'
          memory: 3G
    restart: unless-stopped
    networks:
      - media-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  # MinIO for S3-compatible object storage
  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-08T15-41-24Z
    container_name: minio-storage
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_whats_convert_data:/data
    networks:
      - media-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

volumes:
  minio_whats_convert_data:
    driver: local

networks:
  media-network:
    driver: bridge
