blank_issues_enabled: false
contact_links:
  - name: WhatsApp Media Converter Discussions
    url: https://github.com/guilhermejansen/whats-convert-api/discussions
    about: Ask questions, share ideas, or request support.
